name: Rust PR + Manual Run

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: Choose what to run
        required: true
        type: choice
        options:
          - test
          - build

jobs:
  rust:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show repo structure
        run: |
          pwd
          ls -la
          find . -maxdepth 3 -name Cargo.toml

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: app -> target

      - name: Cargo test on PRs
        if: github.event_name == 'pull_request'
        working-directory: app
        run: cargo test --all --verbose

      - name: Cargo test manually
        if: github.event_name == 'workflow_dispatch' && inputs.action == 'test'
        working-directory: app
        run: cargo test --all --verbose

      - name: Cargo build manually
        if: github.event_name == 'workflow_dispatch' && inputs.action == 'build'
        working-directory: app
        run: cargo build --all --verbose
